sudo: required
language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jobs:
  include:
    - stage: build
      script:
        - ./gradlew assemble
        - ./gradlew check
    - stage: deployToTestEnv
      name: "Deploy to AWS Lambda"
      script:
        - pip install --user awscli
        - ./gradlew buildZip
        - aws cloudformation package --template-file sam-skills-api.yml --output-template-file output-sam-skills-api.yml --s3-bucket cf-template-spring-boot-apps-as-lambda --s3-prefix skills-api-testing
        - aws cloudformation deploy --template-file output-sam-skills-api.yml --stack-name bpm-skills-api-testing --capabilities CAPABILITY_IAM --parameter-overrides "SkillsApiEnvironment=SkillsApiTesting"
    - script:
        - pip install --user awscli
        - npm install -g newman
        - aws cloudformation describe-stacks --stack-name bpm-skills-api-testing | jq -r '.Stacks | .[].Outputs | .[].OutputValue'
        - service_url=$(jq -r '.[] | .[] | .name' test.json)
        - echo $service_url
        - newman run postman/collection.json
      name: "Perform Postman tests"
stages:
  - name: build
  - name: deployToTestEnv
    if: type = pull_request
after_success:
  - bash <(curl -s https://codecov.io/bash)
