AWSTemplateFormatVersion: '2010-09-09'
Description: BpmSkills
Outputs:
  SkillsApi:
    Description: URL for application
    Export:
      Name: SkillsApi
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/skills
Resources:
  SkillsApiLambda:
    Properties:
      CodeUri: s3://cf-template-spring-boot-apps-as-lambda/skills-api/22f93c44d3d485d7225d03eb36b1ed68
      Events:
        GetResource:
          Properties:
            Method: any
            Path: /{proxy+}
          Type: Api
      Handler: com.ioet.bpm.skills.aws.handler.AwsLambdaHandler::handleRequest
      MemorySize: 1512
      Role: arn:aws:iam::524819651720:role/API-lambda-deployment
      Runtime: java8
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
